org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.248
loader_version_range=[1,)

mod_id=pale_mirror
mod_name=Pale Mirror
mod_license=All Rights Reserved
mod_version=0.1.0-SNAPSHOT
mod_group_id=io.farfrontier.palemirror

crimson_integration_url=https://cdn.modrinth.com/data/hgYbf49J/versions/RZ4LrIs5/crimson_curse-1.4.3.1.jar
crimson_integration_sha512=7dff835f17bca4cf2a4efbf237393ccde1c12e4c334f3b3789d36499e3653c756a0be57af18ddae6e36e40cfcf93b33c21d3f47ce02c2d0a659da39fdb7d424c
