org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.248
loader_version_range=[1,)

mod_id=pale_mirror
mod_name=Pale Mirror
mod_license=All Rights Reserved
mod_version=0.2.0-SNAPSHOT
mod_group_id=io.farfrontier.palemirror

crimson_integration_url=https://cdn.modrinth.com/data/hgYbf49J/versions/RZ4LrIs5/crimson_curse-1.4.3.1.jar
crimson_integration_sha512=7dff835f17bca4cf2a4efbf237393ccde1c12e4c334f3b3789d36499e3653c756a0be57af18ddae6e36e40cfcf93b33c21d3f47ce02c2d0a659da39fdb7d424c
spore_integration_url=https://cdn.modrinth.com/data/X661i40C/versions/DwE3w8IX/spore_1.21.1_2.2.0j_neo.jar
spore_integration_sha512=e9830e70d02aeea60eaf0a0484ca153bb8e5d82665142a9b2bf7130850f083dad6e5f30f10a78e3191819ff093108c07664afaf6625a5e1d3f514c9f67fdd15b
create_integration_version=6.0.10
create_integration_url=https://cdn.modrinth.com/data/LNytGWDc/versions/UjX6dr61/create-1.21.1-6.0.10.jar
create_integration_sha512=11cc8fc049d2f67f6548c7abfada6b82a3adb5c7ca410a742de04bbca76e03862c518721b88d806f6e6d768a4d68531fdb903a85859b25d1484d550cc7bafd4b
ftb_quests_integration_url=https://mediafilez.forgecdn.net/files/8589/821/ftb-quests-neoforge-2101.1.30.jar
ftb_quests_integration_sha512=4e38fe5167004e386189483ff2018ce1910720f3068f082f616a25c8183101d7633fbe029cf85067d652e423c9317ef0e6774cdd73f4d9bc48e15e3b33e060d5
ftb_library_integration_url=https://mediafilez.forgecdn.net/files/8569/579/ftb-library-neoforge-2101.1.35.jar
ftb_library_integration_sha512=cc80e7e5ce1ffce910d684ee27e7cdedb2f80a4e8787b792b6837cd1ccd73228bac933d9e07fc1b6ade440163be67b584b89e59debf8a6731211be49f11d9260
ftb_teams_integration_url=https://mediafilez.forgecdn.net/files/7369/21/ftb-teams-neoforge-2101.1.9.jar
ftb_teams_integration_sha512=f1542136eb2c857c9f278a2fe5b605186f2e1307c1b217812ed3f677b9ef5af01d86cb8269a5ce039325312f7d3f5d2ccb94c364a5aea52c28455de86e1cff9d
architectury_integration_url=https://cdn.modrinth.com/data/lhGA9TYQ/versions/1IiqEQGl/architectury-13.0.11-neoforge.jar
architectury_integration_sha512=d9f7c3bb8162577dfb461ffdf04bd6a3563c7586934a0e2a744c14421beffb8286f0d88d4c758317003f20f99fe8072a39b9d675af061e036970d36db36027f0
millenaire_integration_version=9.0.0-beta.2
millenaire_integration_url=https://www.millenaire.org/api/downloads/9.0.0-beta.2~millenaire-9.0.0-beta.2.jar
millenaire_integration_sha512=d385fd361179950addc20af996cfdd37a8200cf5dcebf06c2888c05c5026d53c85a79ad8f60f8c5709a2ae2ca0cf286b7161311579df9b2eba56baeb9815181b
