name = "Far Frontier"
author = "Far Frontier Pack Team"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "550d19760c4e2d5c9043f3a6523d9447194ec2bdc78e1b7ffb9b18a2cef397c0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
