name = "Far Frontier"
author = "Far Frontier Pack Team"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f5b20939f953678fdacf419d7e0c2675a06b456f9a351497e023948cfd109000"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
