package io.farfrontier.palemirror.domain;

public enum DomainEventType {
    MINE_INFECTED,
    FACILITY_DISABLED,
    THREAT_TIER_ESCALATED,
    SCENARIO_OFFERED,
    SCENARIO_ACCEPTED,
    FACILITY_INVESTIGATED,
    THREAT_CONTROLLER_DESTROYED,
    FACILITY_RECOVERING,
    FACILITY_OPERATIONAL,
    SCENARIO_RESOLVED,
    MATERIALIZATION_CONFIRMED,
    NO_SCENARIO,
    SCENARIO_BLOCKED,
    SCENARIO_RESUMED,
    SETTLEMENT_SUPPLY_DISRUPTED,
    SETTLEMENT_SUPPLY_RESTORED
}
