package io.farfrontier.palemirror.domain;

public enum DomainEventType {
    MINE_INFECTED,
    FACILITY_DISABLED,
    SCENARIO_OFFERED,
    SCENARIO_ACCEPTED,
    FACILITY_INVESTIGATED,
    THREAT_CONTROLLER_DESTROYED,
    FACILITY_RECOVERING,
    FACILITY_OPERATIONAL,
    SCENARIO_RESOLVED,
    MATERIALIZATION_CONFIRMED
}
