package io.farfrontier.palemirror.frontier.v3.model;

import io.farfrontier.palemirror.frontier.v3.api.PhysicalIntentKind;
import io.farfrontier.palemirror.frontier.v3.api.PhysicalIntentStatus;
import io.farfrontier.palemirror.frontier.v3.api.PhysicalPostcondition;
import io.farfrontier.palemirror.frontier.v3.model.navigation.MovementOrder;
import io.farfrontier.palemirror.frontier.v3.model.execution.ActorActivityKind;

import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;

/**
 * Stable, explicit persisted tags for every currently durable Frontier v3 enum.
 *
 * <p>The listed values deliberately preserve the historic byte assignments, but the mapping
 * is now a schema contract instead of an implication of Java declaration order.  New values
 * must reserve an explicit, never-reused tag here; removed tags remain reserved forever.</p>
 */
public final class FrontierWireTags {
    private static final Map<Class<?>, Map<Integer, ? extends Enum<?>>> BY_TYPE = Map.ofEntries(
            entry(ActorActivityKind.class,
                    tag(10, ActorActivityKind.PRESENCE), tag(11, ActorActivityKind.MEAL), tag(12, ActorActivityKind.SERVICE_EXIT),
                    tag(13, ActorActivityKind.FIELD_HARVEST), tag(14, ActorActivityKind.PRODUCTION), tag(15, ActorActivityKind.LOGISTICS),
                    tag(16, ActorActivityKind.ROUTE_PATROL), tag(17, ActorActivityKind.SETTLEMENT_ASSAULT), tag(18, ActorActivityKind.ENGINEERING_WORK),
                    tag(19, ActorActivityKind.SETTLEMENT_SERVICE), tag(20, ActorActivityKind.MEDICAL_TREATMENT), tag(21, ActorActivityKind.TRANSIT),
                    tag(22, ActorActivityKind.SCOUT_PATROL), tag(23, ActorActivityKind.HIVE_TASK_ASSEMBLY), tag(24, ActorActivityKind.HIVE_TASK_RETURN),
                    tag(25, ActorActivityKind.OPERATION_ASSEMBLY), tag(26, ActorActivityKind.ENGINEERING_ASSEMBLY),
                    tag(27, ActorActivityKind.ROUTE_INTERCEPTION), tag(28, ActorActivityKind.COURIER)),
            entry(ActorKind.class, tag(0, ActorKind.RESIDENT), tag(1, ActorKind.BIOFORM)),
            entry(ResidentMealResourceEffectObserved.Outcome.class,
                    tag(10, ResidentMealResourceEffectObserved.Outcome.TAKE_UNAPPLIED),
                    tag(11, ResidentMealResourceEffectObserved.Outcome.TAKE_APPLIED),
                    tag(12, ResidentMealResourceEffectObserved.Outcome.CONSUMPTION_APPLIED)),
            entry(ResidentMealPortionDispositionObserved.Outcome.class,
                    tag(10, ResidentMealPortionDispositionObserved.Outcome.MISSING_BEFORE_LOOT),
                    tag(11, ResidentMealPortionDispositionObserved.Outcome.WORLD_DROP)),
            entry(ResidentMealResourceObligation.CustodyState.class,
                    tag(10, ResidentMealResourceObligation.CustodyState.SOURCE_TAKE_PENDING),
                    tag(11, ResidentMealResourceObligation.CustodyState.ACTOR_PORTION),
                    tag(12, ResidentMealResourceObligation.CustodyState.ACTOR_CONSUMPTION_PENDING)),
            entry(ActorLifeStatus.class,
                    tag(0, ActorLifeStatus.ALIVE), tag(1, ActorLifeStatus.DEAD)),
            entry(AmbientGoalKind.class,
                    tag(0, AmbientGoalKind.WORK), tag(1, AmbientGoalKind.GUARD), tag(2, AmbientGoalKind.PATROL), tag(3, AmbientGoalKind.SCOUT_PATROL),
                    tag(4, AmbientGoalKind.TRANSIT), tag(5, AmbientGoalKind.OPERATION_ASSEMBLY), tag(6, AmbientGoalKind.ENGINEERING_ASSEMBLY),
                    tag(7, AmbientGoalKind.HIVE_TASK_ASSEMBLY), tag(8, AmbientGoalKind.HIVE_TASK_RETURN), tag(9, AmbientGoalKind.MEAL),
                    tag(10, AmbientGoalKind.ACTOR_MOVEMENT)),
            entry(AmbientLeaseStatus.class,
                    tag(0, AmbientLeaseStatus.PREPARED), tag(1, AmbientLeaseStatus.HOT), tag(2, AmbientLeaseStatus.DRAINING), tag(3, AmbientLeaseStatus.CLOSED),
                    tag(4, AmbientLeaseStatus.UNKNOWN_AFTER_RESTART)),
            entry(BioformChassis.class,
                    tag(10, BioformChassis.RUNT), tag(11, BioformChassis.OVERSEER), tag(12, BioformChassis.SENTINEL)),
            entry(BioformMutation.class,
                    tag(10, BioformMutation.EXPLOSIVE), tag(11, BioformMutation.MUCUS), tag(12, BioformMutation.ARMORED),
                    tag(13, BioformMutation.SPORE), tag(14, BioformMutation.CARRIER)),
            entry(BioformAssignment.class,
                    tag(10, BioformAssignment.WATCH), tag(11, BioformAssignment.SCOUT), tag(12, BioformAssignment.HARVEST),
                    tag(13, BioformAssignment.CARRY), tag(14, BioformAssignment.REPAIR), tag(15, BioformAssignment.DEFEND),
                    tag(16, BioformAssignment.ASSAULT), tag(17, BioformAssignment.SIEGE), tag(18, BioformAssignment.RETREAT)),
            entry(CompanyPurpose.class,
                    tag(0, CompanyPurpose.WORKS)),
            entry(ClaimPurpose.class,
                    tag(0, ClaimPurpose.PRODUCTION_WORK), tag(1, ClaimPurpose.HIVE_GROWTH),
                    tag(2, ClaimPurpose.SETTLEMENT_RATION), tag(3, ClaimPurpose.SUPPLY_CONTRACT),
                    tag(4, ClaimPurpose.EXTERNAL_RESERVATION), tag(5, ClaimPurpose.RESIDENT_MEAL), tag(6, ClaimPurpose.GOODS_TRADE)),
            entry(CompanyStatus.class,
                    tag(0, CompanyStatus.ACTIVE), tag(1, CompanyStatus.INSOLVENT), tag(2, CompanyStatus.DISSOLVED)),
            entry(ContainerSurfaceStatus.class,
                    tag(0, ContainerSurfaceStatus.UNMATERIALIZED), tag(1, ContainerSurfaceStatus.PREPARED), tag(2, ContainerSurfaceStatus.ACTIVE),
                    tag(3, ContainerSurfaceStatus.CONFLICT)),
            entry(ContractStatus.class,
                    tag(0, ContractStatus.ORDERED), tag(1, ContractStatus.LOADED), tag(2, ContractStatus.DELIVERED), tag(3, ContractStatus.INTERRUPTED)),
            entry(EconomicAccountStatus.class,
                    tag(0, EconomicAccountStatus.ACTIVE), tag(1, EconomicAccountStatus.INSOLVENT)),
            entry(EconomicOwnerKind.class,
                    tag(0, EconomicOwnerKind.SETTLEMENT_TREASURY), tag(1, EconomicOwnerKind.HIVE_COLLECTIVE), tag(2, EconomicOwnerKind.PUBLIC_INFRASTRUCTURE),
                    tag(3, EconomicOwnerKind.COMPANY), tag(4, EconomicOwnerKind.RESIDENT)),
            entry(EngineeringJourneyPurpose.class,
                    tag(0, EngineeringJourneyPurpose.MUSTER_DEPOT), tag(1, EngineeringJourneyPurpose.WORKSITE), tag(2, EngineeringJourneyPurpose.RETURN_DEPOT)),
            entry(EmploymentContractStatus.class,
                    tag(0, EmploymentContractStatus.ACTIVE), tag(1, EmploymentContractStatus.SUSPENDED), tag(2, EmploymentContractStatus.TERMINATED)),
            entry(EmploymentTerminationReason.class,
                    tag(0, EmploymentTerminationReason.DEATH)),
            entry(ExplosionItemImpact.Outcome.class,
                    tag(0, ExplosionItemImpact.Outcome.RETAINED), tag(1, ExplosionItemImpact.Outcome.TRANSFERRED), tag(2, ExplosionItemImpact.Outcome.DESTROYED),
                    tag(3, ExplosionItemImpact.Outcome.CONFLICT)),
            entry(GrayboxSemanticPart.class,
                    tag(0, GrayboxSemanticPart.FOUNDATION), tag(1, GrayboxSemanticPart.WALL), tag(2, GrayboxSemanticPart.ROOF), tag(3, GrayboxSemanticPart.HIVE_TISSUE),
                    tag(4, GrayboxSemanticPart.ROUTE_SURFACE), tag(5, GrayboxSemanticPart.PUBLIC_ACCESS_SURFACE), tag(6, GrayboxSemanticPart.INFECTION_SURFACE),
                    tag(7, GrayboxSemanticPart.WORKSITE_STAGING), tag(8, GrayboxSemanticPart.ROUTE_FOUNDATION), tag(9, GrayboxSemanticPart.COCOON),
                    tag(10, GrayboxSemanticPart.WORKSHOP_INPUT_STATION), tag(11, GrayboxSemanticPart.WORKSHOP_PROCESS_STATION)),
            entry(BioformLifecyclePhase.class,
                    tag(10, BioformLifecyclePhase.DORMANT), tag(11, BioformLifecyclePhase.WAKING), tag(12, BioformLifecyclePhase.ASSEMBLING),
                    tag(13, BioformLifecyclePhase.ACTIVE), tag(14, BioformLifecyclePhase.RETURNING), tag(15, BioformLifecyclePhase.RECOVERING)),
            entry(HiveMobilizationStatus.class,
                    tag(0, HiveMobilizationStatus.WAKING), tag(1, HiveMobilizationStatus.RELEASING),
                    tag(2, HiveMobilizationStatus.ASSEMBLING), tag(3, HiveMobilizationStatus.CONFLICT),
                    tag(4, HiveMobilizationStatus.DEPARTED), tag(5, HiveMobilizationStatus.COMPLETED),
                    tag(6, HiveMobilizationStatus.RETURNING)),
            entry(HiveMobilizationConflictReason.class,
                    tag(0, HiveMobilizationConflictReason.COCOON_CHANGED), tag(1, HiveMobilizationConflictReason.UNKNOWN_AFTER_RESTART),
                    tag(2, HiveMobilizationConflictReason.ASSEMBLY_PATH_BLOCKED), tag(3, HiveMobilizationConflictReason.DEPARTURE_UNAVAILABLE)),
            entry(HiveCommandAuthorityKind.class,
                    tag(0, HiveCommandAuthorityKind.RELAY), tag(1, HiveCommandAuthorityKind.OVERSEER)),
            entry(HiveCommandSignalPhase.class,
                    tag(0, HiveCommandSignalPhase.CONNECTED), tag(1, HiveCommandSignalPhase.SIGNAL_MEMORY),
                    tag(2, HiveCommandSignalPhase.INSTINCT), tag(3, HiveCommandSignalPhase.RECLAIMED)),
            entry(RouteMaintenanceStatus.class,
                    tag(0, RouteMaintenanceStatus.BUILDING), tag(1, RouteMaintenanceStatus.READY), tag(2, RouteMaintenanceStatus.CONFLICT)),
            entry(HiveDoctrine.class,
                    tag(0, HiveDoctrine.CONSOLIDATE), tag(1, HiveDoctrine.EXPAND), tag(2, HiveDoctrine.INTERDICT)),
            entry(HiveGrowthBlockReason.class,
                    tag(0, HiveGrowthBlockReason.BIOMASS_UNAVAILABLE), tag(1, HiveGrowthBlockReason.GROWTH_CAPACITY_UNAVAILABLE),
                    tag(2, HiveGrowthBlockReason.PHYSICAL_CONSUMPTION_UNKNOWN)),
            entry(HiveNutrientReceiptStatus.class,
                    tag(0, HiveNutrientReceiptStatus.STORED), tag(1, HiveNutrientReceiptStatus.CONSUMED)),
            entry(HiveNutrientTransferBlockReason.class,
                    tag(0, HiveNutrientTransferBlockReason.ENDPOINT_MATERIALIZED), tag(1, HiveNutrientTransferBlockReason.TARGET_SLOT_UNAVAILABLE),
                    tag(2, HiveNutrientTransferBlockReason.CARGO_CUSTODY_LOST)),
            entry(HiveNutrientTransferPhase.class,
                    tag(0, HiveNutrientTransferPhase.IN_TRANSIT), tag(1, HiveNutrientTransferPhase.BLOCKED), tag(2, HiveNutrientTransferPhase.DEPARTURE_PENDING),
                    tag(3, HiveNutrientTransferPhase.ARRIVAL_PENDING)),
            entry(HiveOrganKind.class,
                    tag(10, HiveOrganKind.GANGLION), tag(11, HiveOrganKind.RELAY), tag(12, HiveOrganKind.STORE),
                    tag(13, HiveOrganKind.DIGESTER), tag(14, HiveOrganKind.BROOD), tag(15, HiveOrganKind.HIBERNACULUM),
                    tag(16, HiveOrganKind.MORPHER), tag(17, HiveOrganKind.SPORULATOR), tag(18, HiveOrganKind.SENSOR)),
            entry(HumanCapability.class,
                    tag(0, HumanCapability.AGRICULTURE), tag(1, HumanCapability.EXTRACTION), tag(2, HumanCapability.INDUSTRY),
                    tag(3, HumanCapability.ENGINEERING), tag(4, HumanCapability.LOGISTICS), tag(5, HumanCapability.MEDICINE),
                    tag(6, HumanCapability.SECURITY), tag(7, HumanCapability.CIVIC)),
            entry(MedicalEvacuationStatus.class,
                    tag(0, MedicalEvacuationStatus.PREPARED), tag(1, MedicalEvacuationStatus.TREATING),
                    tag(2, MedicalEvacuationStatus.COMPLETED), tag(3, MedicalEvacuationStatus.BLOCKED),
                    tag(4, MedicalEvacuationStatus.UNKNOWN_AFTER_RESTART)),
            entry(InventoryConflictKind.class,
                    tag(0, InventoryConflictKind.MISSING), tag(1, InventoryConflictKind.FOREIGN_OR_DUPLICATE)),
            entry(MarketDemandCancellationReason.class,
                    tag(0, MarketDemandCancellationReason.PRODUCTION_BLOCKED), tag(1, MarketDemandCancellationReason.TASK_NO_LONGER_PENDING)),
            entry(MarketDemandStatus.class,
                    tag(0, MarketDemandStatus.OPEN), tag(1, MarketDemandStatus.ORDERED), tag(2, MarketDemandStatus.FULFILLED), tag(3, MarketDemandStatus.CANCELLED),
                    tag(4, MarketDemandStatus.EXPIRED)),
            entry(MarketWorkOrderStatus.class,
                    tag(0, MarketWorkOrderStatus.ACCEPTED), tag(1, MarketWorkOrderStatus.FULFILLED), tag(2, MarketWorkOrderStatus.CANCELLED),
                    tag(3, MarketWorkOrderStatus.CONFLICT)),
            entry(OperationAssemblyDeferral.Reason.class,
                    tag(0, OperationAssemblyDeferral.Reason.LOADED_WORLD_OBSTRUCTION)),
            entry(PhysicalDeltaKind.class,
                    tag(0, PhysicalDeltaKind.KNOWN_SEMANTIC_LOSS), tag(1, PhysicalDeltaKind.UNKNOWN_SCAR)),
            entry(DeferredAftermathKnowledge.class,
                    tag(0, DeferredAftermathKnowledge.KNOWN_CLEAR), tag(1, DeferredAftermathKnowledge.UNKNOWN_SHIELDING)),
            entry(DeferredAftermathCellStatus.class,
                    tag(0, DeferredAftermathCellStatus.PENDING), tag(1, DeferredAftermathCellStatus.RUNNING), tag(2, DeferredAftermathCellStatus.REALIZED), tag(3, DeferredAftermathCellStatus.CONFLICTED)),
            entry(PhysicalIntentKind.class,
                    tag(0, PhysicalIntentKind.CARGO_HANDOFF), tag(1, PhysicalIntentKind.STRUCTURAL_REPAIR), tag(2, PhysicalIntentKind.ROUTE_CONSTRUCTION),
                    tag(3, PhysicalIntentKind.DECONTAMINATION), tag(4, PhysicalIntentKind.EXPLOSION), tag(5, PhysicalIntentKind.SCENE_STRIKE),
                    tag(6, PhysicalIntentKind.EXACT_ITEM_CONSUMPTION), tag(7, PhysicalIntentKind.RESOURCE_SITE_PREPARATION), tag(8, PhysicalIntentKind.RESOURCE_SITE_HARVEST),
                    tag(9, PhysicalIntentKind.PRODUCTION_TRANSFORMATION), tag(10, PhysicalIntentKind.CARGO_LOADING),
                    tag(11, PhysicalIntentKind.ROUTE_CONSTRUCTION_MATERIAL_LOADING), tag(12, PhysicalIntentKind.HIVE_NUTRIENT_DEPARTURE),
                    tag(13, PhysicalIntentKind.HIVE_NUTRIENT_ARRIVAL), tag(14, PhysicalIntentKind.EQUIPMENT_ISSUE),
                    tag(15, PhysicalIntentKind.EQUIPMENT_RETURN), tag(16, PhysicalIntentKind.ROUTE_MAINTENANCE),
                    tag(17, PhysicalIntentKind.ROUTE_MAINTENANCE_MATERIAL_LOADING), tag(18, PhysicalIntentKind.SETTLEMENT_SERVICE_INPUT_ISSUE)),
            entry(PhysicalIntentStatus.class,
                    tag(0, PhysicalIntentStatus.PREPARED), tag(1, PhysicalIntentStatus.RUNNING), tag(2, PhysicalIntentStatus.CONFIRMED),
                    tag(3, PhysicalIntentStatus.UNKNOWN_AFTER_RESTART), tag(4, PhysicalIntentStatus.CONFLICTED)),
            entry(ResourceSiteConflictReason.class,
                    tag(0, ResourceSiteConflictReason.PLAYER_REMOVED_MANAGED_CELL), tag(1, ResourceSiteConflictReason.EXPLOSION_DAMAGED_MANAGED_CELL),
                    tag(2, ResourceSiteConflictReason.OBSERVED_MANAGED_CELL_MISMATCH), tag(3, ResourceSiteConflictReason.RECOVERY_UNRESOLVED),
                    tag(4, ResourceSiteConflictReason.WORKER_DIED), tag(5, ResourceSiteConflictReason.CARRIER_FENCE_UNRESOLVED),
                    tag(6, ResourceSiteConflictReason.FIELD_ROUTE_BLOCKED_SUPPORT), tag(7, ResourceSiteConflictReason.FIELD_ROUTE_BLOCKED_CLEARANCE),
                    tag(8, ResourceSiteConflictReason.FIELD_ROUTE_BLOCKED_MEDIUM), tag(9, ResourceSiteConflictReason.FIELD_ROUTE_OFF_CONTRACT)),
            entry(ResourceSiteConflictSource.class,
                    tag(0, ResourceSiteConflictSource.LAWFUL_LIFECYCLE_LAG), tag(1, ResourceSiteConflictSource.PLAYER_WORLD_OBSERVATION),
                    tag(2, ResourceSiteConflictSource.EXPLOSION_WITNESS), tag(3, ResourceSiteConflictSource.RESTART_RECONCILIATION),
                    tag(4, ResourceSiteConflictSource.PHYSICAL_INTENT_RECOVERY), tag(5, ResourceSiteConflictSource.LIFECYCLE_RECONCILIATION),
                    tag(6, ResourceSiteConflictSource.WORKER_DEATH), tag(7, ResourceSiteConflictSource.ADAPTER_WRITE_FAILURE),
                    tag(8, ResourceSiteConflictSource.SCENE_CARRIER_FENCE), tag(9, ResourceSiteConflictSource.SCENE_TRAVERSAL)),
            entry(ResourceSiteConflictPolicy.class,
                    tag(0, ResourceSiteConflictPolicy.TERMINAL_REPAIR_REQUIRED), tag(1, ResourceSiteConflictPolicy.RECOVERY_INSPECTION_REQUIRED)),
            entry(PhysicalPostcondition.class,
                    tag(0, PhysicalPostcondition.CARGO_HANDOFF_OBSERVED), tag(1, PhysicalPostcondition.STRUCTURAL_REPAIR_OBSERVED),
                    tag(2, PhysicalPostcondition.ROUTE_CONSTRUCTION_OBSERVED), tag(3, PhysicalPostcondition.DECONTAMINATION_OBSERVED),
                    tag(4, PhysicalPostcondition.EXPLOSION_OBSERVED), tag(5, PhysicalPostcondition.SCENE_STRIKE_OBSERVED),
                    tag(6, PhysicalPostcondition.EXACT_ITEM_CONSUMED_OBSERVED), tag(7, PhysicalPostcondition.RESOURCE_SITE_PREPARED_OBSERVED),
                    tag(8, PhysicalPostcondition.RESOURCE_SITE_HARVESTED_OBSERVED), tag(9, PhysicalPostcondition.PRODUCTION_TRANSFORMED_OBSERVED),
                    tag(10, PhysicalPostcondition.CARGO_LOADED_FROM_DEPOT_OBSERVED), tag(11, PhysicalPostcondition.ROUTE_CONSTRUCTION_MATERIAL_LOADED_OBSERVED),
                    tag(12, PhysicalPostcondition.HIVE_NUTRIENT_DEPARTED_OBSERVED), tag(13, PhysicalPostcondition.HIVE_NUTRIENT_ARRIVED_OBSERVED),
                    tag(14, PhysicalPostcondition.EQUIPMENT_ISSUED_OBSERVED), tag(15, PhysicalPostcondition.EQUIPMENT_RETURNED_OBSERVED),
                    tag(16, PhysicalPostcondition.ROUTE_MAINTENANCE_OBSERVED), tag(17, PhysicalPostcondition.ROUTE_MAINTENANCE_MATERIAL_LOADED_OBSERVED),
                    tag(18, PhysicalPostcondition.SETTLEMENT_SERVICE_INPUT_ISSUED_OBSERVED)),
            entry(ProductionBlockReason.class,
                    tag(0, ProductionBlockReason.INPUT_UNAVAILABLE), tag(1, ProductionBlockReason.OUTPUT_STORAGE_UNAVAILABLE), tag(2, ProductionBlockReason.FACILITY_UNAVAILABLE),
                    tag(3, ProductionBlockReason.WORKER_UNAVAILABLE), tag(4, ProductionBlockReason.FINANCE_UNAVAILABLE), tag(5, ProductionBlockReason.ROUTE_BLOCKED),
                    tag(6, ProductionBlockReason.RELATIONSHIP_CONFLICT)),
            entry(ResidentHealthStatus.class,
                    tag(0, ResidentHealthStatus.HEALTHY), tag(1, ResidentHealthStatus.EXPOSED), tag(2, ResidentHealthStatus.INFECTED), tag(3, ResidentHealthStatus.RECOVERING)),
            entry(ResidentMigrationBlockReason.class,
                    tag(0, ResidentMigrationBlockReason.QUARANTINE), tag(1, ResidentMigrationBlockReason.DESTINATION_HOUSING_LOST),
                    tag(2, ResidentMigrationBlockReason.ROUTE_OBSTRUCTED)),
            entry(ResidentMigrationStatus.class,
                    tag(0, ResidentMigrationStatus.EN_ROUTE), tag(1, ResidentMigrationStatus.BLOCKED)),
            entry(ResidentNutritionStatus.class,
                    tag(0, ResidentNutritionStatus.NOURISHED), tag(1, ResidentNutritionStatus.HUNGRY), tag(2, ResidentNutritionStatus.STARVING)),
            entry(ResidentMeal.Phase.class,
                    tag(0, ResidentMeal.Phase.MOVE), tag(1, ResidentMeal.Phase.TAKE),
                    tag(2, ResidentMeal.Phase.CONSUME), // tag3 (legacy post-consumption RETURN) is retired
                    tag(4, ResidentMeal.Phase.CLEAR_ACCESS)),
            entry(ResidentActivityChoice.Wait.class,
                    tag(0, ResidentActivityChoice.Wait.SAFE_CHECKPOINT),
                    tag(1, ResidentActivityChoice.Wait.SOURCE_UNAVAILABLE),
                    tag(2, ResidentActivityChoice.Wait.ROUTE_BLOCKED),
                    tag(3, ResidentActivityChoice.Wait.HAND_OCCUPIED)),
            entry(SettlementDailySchedule.Window.class,
                    tag(0, SettlementDailySchedule.Window.WORK), tag(1, SettlementDailySchedule.Window.FREE)),
            entry(ResidentProfession.class,
                    tag(0, ResidentProfession.AGRICULTURAL_WORKER), tag(1, ResidentProfession.EXTRACTOR), tag(2, ResidentProfession.INDUSTRIAL_WORKER),
                    tag(3, ResidentProfession.ENGINEER), tag(4, ResidentProfession.LOGISTICIAN), tag(5, ResidentProfession.MEDICAL_WORKER),
                    tag(6, ResidentProfession.SECURITY_WORKER), tag(7, ResidentProfession.CIVIC_WORKER), tag(8, ResidentProfession.BAKER)),
            entry(ResidentRole.class,
                    tag(0, ResidentRole.FARMER), tag(1, ResidentRole.BUILDER), tag(2, ResidentRole.CRAFTER), tag(3, ResidentRole.GUARD), tag(4, ResidentRole.MEDIC),
                    tag(5, ResidentRole.HAULER)),
            entry(ResidentSkill.class,
                    tag(0, ResidentSkill.AGRICULTURE), tag(1, ResidentSkill.BUILDING), tag(2, ResidentSkill.CRAFTING), tag(3, ResidentSkill.SECURITY),
                    tag(4, ResidentSkill.MEDICINE), tag(5, ResidentSkill.LOGISTICS)),
            entry(ResourceSitePhase.class,
                    tag(0, ResourceSitePhase.UNPREPARED), tag(1, ResourceSitePhase.GROWING), tag(2, ResourceSitePhase.READY), tag(3, ResourceSitePhase.HARVESTING),
                    tag(4, ResourceSitePhase.CONFLICT), tag(5, ResourceSitePhase.DESTROYED)),
            entry(RouteConstructionStatus.class,
                    tag(0, RouteConstructionStatus.BUILDING), tag(1, RouteConstructionStatus.CONFLICT), tag(2, RouteConstructionStatus.READY)),
            entry(RouteEngagementOutcome.class,
                    tag(0, RouteEngagementOutcome.HIVE_VICTORY), tag(1, RouteEngagementOutcome.SETTLEMENT_VICTORY), tag(2, RouteEngagementOutcome.ABORTED)),
            entry(RouteEngagementStatus.class,
                    tag(0, RouteEngagementStatus.APPROACHING), tag(1, RouteEngagementStatus.WAITING_FOR_INTERCEPT), tag(2, RouteEngagementStatus.COLD_COMBAT),
                    tag(3, RouteEngagementStatus.HOT), tag(4, RouteEngagementStatus.RESOLVED), tag(5, RouteEngagementStatus.UNKNOWN_AFTER_RESTART),
                    tag(6, RouteEngagementStatus.CONFLICT)),
            entry(RoutePatrolStatus.class,
                    tag(0, RoutePatrolStatus.ASSEMBLING), tag(1, RoutePatrolStatus.EN_ROUTE), tag(2, RoutePatrolStatus.ROUTE_CLEAR),
                    tag(3, RoutePatrolStatus.OBSTRUCTION_CONFIRMED), tag(4, RoutePatrolStatus.BLOCKED), tag(5, RoutePatrolStatus.FAILED)),
            entry(RoutePatrolBlockReason.class,
                    tag(0, RoutePatrolBlockReason.NO_OPEN_RETAINED_EDGE), tag(1, RoutePatrolBlockReason.MISSING_OWNED_BODY),
                    tag(2, RoutePatrolBlockReason.CHANGED_OWNED_BODY), tag(3, RoutePatrolBlockReason.OCCUPIED_NEXT_BODY),
                    tag(4, RoutePatrolBlockReason.DAMAGED_SUPPORT), tag(5, RoutePatrolBlockReason.PLAYER_OR_WORLD_OBSTRUCTION),
                    tag(6, RoutePatrolBlockReason.RECOVERY_UNRESOLVED)),
            entry(ExpeditionMarchIssueKind.class,
                    tag(0, ExpeditionMarchIssueKind.BLOCKED_EDGE), tag(1, ExpeditionMarchIssueKind.OCCUPIED_NEXT_BODY),
                    tag(2, ExpeditionMarchIssueKind.MISSING_OWNED_BODY), tag(3, ExpeditionMarchIssueKind.CONTROLLER_LOST)),
            entry(RouteUnitDuty.class,
                    tag(0, RouteUnitDuty.PATROL_LEADER), tag(1, RouteUnitDuty.SCOUT), tag(2, RouteUnitDuty.CARGO_CREW), tag(3, RouteUnitDuty.ESCORT)),
            entry(RouteUnitKind.class,
                    tag(0, RouteUnitKind.PATROL), tag(1, RouteUnitKind.CARGO_ESCORT)),
            entry(SceneLeaseStatus.class,
                    tag(0, SceneLeaseStatus.PREPARED), tag(1, SceneLeaseStatus.HOT), tag(2, SceneLeaseStatus.DRAINING), tag(3, SceneLeaseStatus.CLOSED),
                    tag(4, SceneLeaseStatus.UNKNOWN_AFTER_RESTART), tag(5, SceneLeaseStatus.CONFLICT)),
            entry(SettlementAssaultOutcome.class,
                    tag(0, SettlementAssaultOutcome.HIVE_VICTORY), tag(1, SettlementAssaultOutcome.SETTLEMENT_VICTORY), tag(2, SettlementAssaultOutcome.ABORTED)),
            entry(SettlementAssaultStatus.class,
                    tag(0, SettlementAssaultStatus.APPROACHING), tag(1, SettlementAssaultStatus.WAITING_FOR_BATTLE), tag(2, SettlementAssaultStatus.COLD_COMBAT),
                    tag(3, SettlementAssaultStatus.HOT), tag(4, SettlementAssaultStatus.RESOLVED), tag(5, SettlementAssaultStatus.UNKNOWN_AFTER_RESTART),
                    tag(6, SettlementAssaultStatus.CONFLICT)),
            entry(SettlementProvisionStatus.class,
                    tag(0, SettlementProvisionStatus.IDLE), tag(1, SettlementProvisionStatus.IN_PROGRESS), tag(2, SettlementProvisionStatus.SECURE),
                    tag(3, SettlementProvisionStatus.RATIONED), tag(4, SettlementProvisionStatus.SHORTAGE), tag(5, SettlementProvisionStatus.CONFLICT)),
            entry(SettlementQuarantineStatus.class,
                    tag(0, SettlementQuarantineStatus.NORMAL), tag(1, SettlementQuarantineStatus.QUARANTINED)),
            entry(DecisionAuthorityKind.class,
                    tag(0, DecisionAuthorityKind.SETTLEMENT), tag(1, DecisionAuthorityKind.HIVEMIND)),
            entry(TacticalPlanPhase.class,
                    tag(0, TacticalPlanPhase.ASSEMBLE), tag(1, TacticalPlanPhase.TRAVEL), tag(2, TacticalPlanPhase.CONTACT),
                    tag(3, TacticalPlanPhase.RETURN), tag(4, TacticalPlanPhase.RETREAT), tag(5, TacticalPlanPhase.COMPLETE), tag(6, TacticalPlanPhase.ABORTED)),
            entry(TacticalRole.class,
                    tag(0, TacticalRole.LEADER), tag(1, TacticalRole.ESCORT), tag(2, TacticalRole.CARGO_CARRIER), tag(3, TacticalRole.SCOUT),
                    tag(4, TacticalRole.DEFENDER), tag(5, TacticalRole.ATTACKER), tag(6, TacticalRole.OVERSEER)),
            entry(TacticalBehaviour.class,
                    tag(0, TacticalBehaviour.HOLD_FORMATION), tag(1, TacticalBehaviour.ADVANCE_CHECKPOINT), tag(2, TacticalBehaviour.DEFEND_CARGO),
                    tag(3, TacticalBehaviour.OBSERVE_OBSTRUCTION), tag(4, TacticalBehaviour.ENGAGE_WITHIN_ENVELOPE), tag(5, TacticalBehaviour.RETREAT_TO_PORT)),
            entry(StrategicObjectiveKind.class,
                    tag(0, StrategicObjectiveKind.SETTLEMENT_CONTAIN_LOCAL_INFECTION), tag(1, StrategicObjectiveKind.HIVE_EXPAND_INFECTION),
                    tag(2, StrategicObjectiveKind.HIVE_GROW_ORGANISM), tag(3, StrategicObjectiveKind.HIVE_INTERCEPT_ROUTE_OPERATION),
                    tag(4, StrategicObjectiveKind.HIVE_ASSAULT_SETTLEMENT), tag(5, StrategicObjectiveKind.SETTLEMENT_PRODUCE_BREAD),
                    tag(10, StrategicObjectiveKind.SETTLEMENT_COMPANY_PRODUCTION),
                    tag(6, StrategicObjectiveKind.SETTLEMENT_DELIVER_BREAD_TO_HIVE), tag(7, StrategicObjectiveKind.SETTLEMENT_PATROL_OBSTRUCTED_ROUTE),
                    tag(8, StrategicObjectiveKind.SETTLEMENT_CONSTRUCT_ROUTE_BYPASS), tag(9, StrategicObjectiveKind.SETTLEMENT_HARVEST_RESOURCE_SITE)),
            entry(StrategicObjectiveStatus.class,
                    tag(0, StrategicObjectiveStatus.ACTIVE), tag(1, StrategicObjectiveStatus.BLOCKED), tag(2, StrategicObjectiveStatus.COMPLETED)),
            entry(StrategicTaskKind.class,
                    tag(0, StrategicTaskKind.DECONTAMINATE_INFECTION_CELL), tag(1, StrategicTaskKind.SPREAD_INFECTION_CELL), tag(2, StrategicTaskKind.GROW_HIVE_ORGANISM),
                    tag(3, StrategicTaskKind.INTERCEPT_ROUTE_OPERATION), tag(4, StrategicTaskKind.ASSAULT_SETTLEMENT), tag(5, StrategicTaskKind.PRODUCE_BREAD),
                    tag(6, StrategicTaskKind.PREPARE_BREAD_CARGO), tag(7, StrategicTaskKind.DELIVER_BREAD_TO_HIVE), tag(8, StrategicTaskKind.PATROL_OBSTRUCTED_ROUTE),
                    tag(9, StrategicTaskKind.CONSTRUCT_ROUTE_BYPASS), tag(10, StrategicTaskKind.HARVEST_RESOURCE_SITE)),
            entry(StrategicTaskRequirement.class,
                    tag(0, StrategicTaskRequirement.ACTIVE_INFIRMARY), tag(1, StrategicTaskRequirement.EXACT_DECONTAMINATION_REAGENT),
                    tag(2, StrategicTaskRequirement.OPERATIONAL_GANGLION), tag(3, StrategicTaskRequirement.AVAILABLE_HIVE_GUARD), tag(4, StrategicTaskRequirement.EXACT_HIVE_BIOMASS),
                    tag(5, StrategicTaskRequirement.ACTIVE_WORKSHOP), tag(6, StrategicTaskRequirement.EXACT_WHEAT_INPUT), tag(7, StrategicTaskRequirement.FREE_DEPOT_SLOT),
                    tag(8, StrategicTaskRequirement.EXACT_BREAD_CARGO), tag(9, StrategicTaskRequirement.PASSABLE_SUPPLY_ROUTE), tag(10, StrategicTaskRequirement.AVAILABLE_HAULER),
                    tag(11, StrategicTaskRequirement.AVAILABLE_GUARD), tag(12, StrategicTaskRequirement.CONFIRMED_ROUTE_OBSTRUCTION),
                    tag(13, StrategicTaskRequirement.EXACT_ROUTE_CONSTRUCTION_MATERIAL), tag(14, StrategicTaskRequirement.AVAILABLE_HIVE_BOMBER),
                    tag(15, StrategicTaskRequirement.ACTIVE_FARM), tag(16, StrategicTaskRequirement.AVAILABLE_FARMER)),
            entry(StrategicTaskStatus.class,
                    tag(0, StrategicTaskStatus.PENDING), tag(1, StrategicTaskStatus.ACTIVE), tag(2, StrategicTaskStatus.BLOCKED), tag(3, StrategicTaskStatus.COMPLETED)),
            entry(StructureCondition.class,
                    tag(0, StructureCondition.INTACT), tag(1, StructureCondition.DAMAGED), tag(2, StructureCondition.DESTROYED)),
            entry(TerminalLogisticsReceipt.TerminalLogisticsOutcome.class,
                    tag(0, TerminalLogisticsReceipt.TerminalLogisticsOutcome.DELIVERED), tag(1, TerminalLogisticsReceipt.TerminalLogisticsOutcome.FAILED),
                    tag(2, TerminalLogisticsReceipt.TerminalLogisticsOutcome.INTERRUPTED)),
            entry(TraversalAvailability.class,
                    tag(0, TraversalAvailability.OPEN), tag(1, TraversalAvailability.BLOCKED), tag(2, TraversalAvailability.DAMAGED), tag(3, TraversalAvailability.UNKNOWN)),
            entry(TraversalCapability.class,
                    tag(0, TraversalCapability.PEDESTRIAN), tag(1, TraversalCapability.GROUND_BIOFORM), tag(2, TraversalCapability.RAIL_VEHICLE)),
            entry(MovementOrder.ArrivalPolicy.class,
                    tag(0, MovementOrder.ArrivalPolicy.EXACT_STATION), tag(1, MovementOrder.ArrivalPolicy.ANY_DECLARED_STATION)),
            entry(TraversalKind.class,
                    tag(0, TraversalKind.PEDESTRIAN), tag(1, TraversalKind.GROUND_BIOFORM), tag(2, TraversalKind.RAIL))
);

    private FrontierWireTags() { }

    public static int tag(Enum<?> value) {
        Objects.requireNonNull(value, "persisted enum");
        Map<Integer, ? extends Enum<?>> byTag = BY_TYPE.get(value.getDeclaringClass());
        if (byTag == null) throw new IllegalArgumentException("unregistered persisted enum type: " + value.getDeclaringClass().getName());
        for (Map.Entry<Integer, ? extends Enum<?>> entry : byTag.entrySet()) {
            if (entry.getValue() == value) return entry.getKey();
        }
        throw new IllegalArgumentException("unregistered persisted enum value: " + value);
    }

    public static <E extends Enum<E>> E require(Class<E> type, int tag) {
        Objects.requireNonNull(type, "persisted enum type");
        Map<Integer, ? extends Enum<?>> byTag = BY_TYPE.get(type);
        if (byTag == null) throw new IllegalArgumentException("unregistered persisted enum type: " + type.getName());
        Enum<?> value = byTag.get(tag);
        if (value == null) throw new IllegalArgumentException("unknown " + type.getSimpleName() + " wire tag: " + tag);
        return type.cast(value);
    }

    public static java.util.Set<Class<?>> types() { return BY_TYPE.keySet(); }

    private record Tagged<E extends Enum<E>>(int value, E enumValue) { }

    private static <E extends Enum<E>> Tagged<E> tag(int value, E enumValue) {
        return new Tagged<>(value, Objects.requireNonNull(enumValue, "persisted enum value"));
    }

    @SafeVarargs
    private static <E extends Enum<E>> Map.Entry<Class<?>, Map<Integer, ? extends Enum<?>>> entry(Class<E> type, Tagged<E>... taggedValues) {
        Map<Integer, E> byTag = new LinkedHashMap<>();
        java.util.Set<E> values = new java.util.LinkedHashSet<>();
        for (Tagged<E> tagged : taggedValues) {
            E value = tagged.enumValue();
            if (tagged.value() < 0 || value.getDeclaringClass() != type || byTag.putIfAbsent(tagged.value(), value) != null || !values.add(value)) {
                throw new IllegalArgumentException("invalid stable wire tag registration for " + type.getName());
            }
        }
        return Map.entry(type, Map.copyOf(byTag));
    }
}
