modLoader="javafml"
loaderVersion="${loader_version_range}"
license="All Rights Reserved"

[[mods]]
modId="pale_mirror_visuals"
version="${mod_version}"
displayName="Pale Mirror Visuals"
description='''
Fresh-world authored settlements, infrastructure, residents and dynamic physical state for Pale Mirror.
'''

[[mixins]]
config="pale_mirror_visuals.mixins.json"
requiredMods=["villageroverhaul"]

[[dependencies.pale_mirror_visuals]]
modId="pale_mirror"
type="required"
versionRange="[${mod_version}]"
ordering="AFTER"
side="BOTH"

[[dependencies.pale_mirror_visuals]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.pale_mirror_visuals]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.pale_mirror_visuals]]
modId="geckolib"
type="required"
versionRange="[4.9.2]"
ordering="AFTER"
side="BOTH"

[[dependencies.pale_mirror_visuals]]
modId="villageroverhaul"
type="required"
versionRange="[3.10.17.16]"
ordering="AFTER"
side="BOTH"

[[dependencies.pale_mirror_visuals]]
modId="supplementaries"
type="required"
versionRange="[1.21-3.5.18,)"
ordering="AFTER"
side="BOTH"
