modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description='''
Canonical world simulation, scenarios, materialization and reconciliation for Far Frontier.
'''

[[mixins]]
config="pale_mirror.spore.mixins.json"
requiredMods=["spore"]

[[mixins]]
config="pale_mirror.item_firewall.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
